### ISSUE TITLE
cv2import

### ISSUE THREAD

**Issue by cardenluo** [MarkoCa1/ComfyUI_Segment_Mask#1]
cannot install cv2import 

F:\Blender_ComfyUI_aki\python_embeded\Scripts>pip install cv2import
WARNING: Ignoring invalid distribution -cipy (f:\blender_comfyui_aki\python_embeded\lib\site-packages)
ERROR: Could not find a version that satisfies the requirement cv2import (from versions: none)
ERROR: No matching distribution found for cv2import

**Comment by MarkoCa1** [comment]
Sorry, actually its name should be cv2

**Comment by MarkoCa1** [comment]
Try the new version

**Comment by cardenluo** [comment]
![image](https://github.com/MarkoCa1/ComfyUI_Segment_Mask/assets/133877069/c4ac4468-bb53-421f-9a4e-de8c5e4eb856)
It works well, thank you
