### ISSUE TITLE
How to use it in actual workflow?

### ISSUE THREAD

**Issue by cardenluo** [MarkoCa1/ComfyUI_Segment_Mask#2]
It seems that ComfyUI doesn't fully demonstrate its practical value. It doesn't have the function of automatically recognizing color blocks like WebUI. I tried to use the color recognition node to pick up colors and then export color block masks, but I found that they cannot be output as a common image format.Or can you provide a workflow to demonstrate its practical application?

**Comment by MarkoCa1** [comment]
In my imagination, I first specify a point in the original image, then get the color corresponding to this point in the color block, and then convert the area of the same color into a mask. But I don't have time to finish it now, or you can get the answer in the original author： [segment-anything](https://github.com/facebookresearch/segment-anything)

**Comment by MarkoCa1** [comment]
At present, it is only returned to js for the effect of clicking and cutting out the image.

**Comment by MarkoCa1** [comment]
Now there is a new version available

**Comment by cardenluo** [comment]
I found a place where SAM could be used to monitor color blocks, which would be quite convenient.
![image](https://github.com/MarkoCa1/ComfyUI_Segment_Mask/assets/133877069/344c5dca-2a33-4228-9080-034f71f98b4b)
