### ISSUE TITLE
'SAMWrapper' object has no attribute 'image_encoder' in AutomaticMask Node

### ISSUE THREAD

**Issue by martintomov** [MarkoCa1/ComfyUI_Segment_Mask#4]
## Issue
When using the AutomaticMask (segment anything) node in ComfyUI, I encounter an AttributeError that prevents the node from executing successfully. The full error message is as follows:
```
Error occurred when executing AutomaticMask(segment anything):
'SAMWrapper' object has no attribute 'image_encoder'
```

Could you please help to resolve this issue or provide guidance on how to proceed?
<img width="1213" alt="Screenshot 2024-04-09 at 00 48 31" src="https://github.com/MarkoCa1/ComfyUI_Segment_Mask/assets/101264514/1401d9f3-04dd-4202-a4b0-23e15eccad96">

**Comment by martintomov** [comment]
## Issue solved here:
### https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/547

**Comment by ltdrdata** [comment]
This is fixed. Update Impact Pack to latest version. 
You can use without replace  the node.
