### ISSUE TITLE
Selective Object Segmentation via Prompt or Points of Interest in AutomaticMask 

### ISSUE THREAD

**Issue by martintomov** [MarkoCa1/ComfyUI_Segment_Mask#5]
## Feature Description
Allowing users to select specific objects, or multiple objects within an image, by using **prompts** or **designated points of interest**.

## Use Case
By allowing users to specify which objects they want to segment -- either through a text prompt (e.g., "segment the dog and the ball") or by selecting points of interest on the image -- we can enhance the node's flexibility and accuracy for targeted segmentation tasks.

The fact that this ComfyUI SAM node works on non-CUDA machines is a significant improvement from other nodes that I have tested and it only lacks in not being able to specify which objects I want to segment. Check [here](https://github.com/storyicon/comfyui_segment_anything/issues/60).

**Comment by MarkoCa1** [comment]
I am currently quite busy and will take some time in the future to complete the **designed points of interest**
﻿

**Comment by MarkoCa1** [comment]
Now there is a new version available
